kind: pipeline
type: docker
name: kube-ctl-web-publish

environment:
  GOOS: linux
  GOARCH: amd64

steps:
  - name: build
    image: plugins/docker
    volumes:
      - name: hosts
        path: /etc/hosts
      - name: docker-ca
        path: /etc/docker
      - name: dockersock
        path: /var/run/docker.sock
    settings:
      username: admin
      password:
        from_secret: harbor_password
      repo: harbor.cfckube.com/kubefrank/kube-ctl-web
      registry: harbor.cfckube.com
      tags:
        - v1.0

  - name: deploy via ssh
    image: appleboy/drone-ssh:1.6.13
    settings:
      host: 172.20.2.17
      username: frank  # Windows 上配置的可 ssh 用户
      password:
        from_secret: ssh_password
      port: 22
      script:
        - docker stop kube-ctl-web || true
        - docker rm kube-ctl-web || true
        - docker pull harbor.cfckube.com/kubefrank/kube-ctl-web:v1.0
        - docker run --name kube-ctl-web --restart=always -d -p 8081:80 -e BACKEND_HOST=http://172.20.2.17:8083/ harbor.cfckube.com/kubefrank/kube-ctl-web:v1.0

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
