kind: pipeline
type: docker
name: kube-ctl-web-publish

steps:
  - name: build and push to harbor
    image: plugins/docker:20.14.2
    settings:
      username: admin
      password:
        from_secret: harbor_password
      repo: harbor.cfckube.com/kubefrank/kube-ctl-web
      registry: harbor.cfckube.com
      tags:
        - v1.0
    extra_hosts:
      - "harbor.cfckube.com:172.20.2.17"

  - name: deploy via ssh
    image: appleboy/drone-ssh:1.6.13
    settings:
      host: 172.20.2.17           # Windows 主机地址
      username: frank             # Windows 中已开启 SSH 的用户名
      password:
        from_secret: ssh_password
      port: 22                    # 默认 SSH 端口，确保 Windows 已开放
      script:
        - if [ $(docker ps -a | grep kube-ctl-web | wc -l) -ge 1 ]; then docker stop kube-ctl-web && docker rm kube-ctl-web; fi
        - docker pull harbor.cfckube.com/kubefrank/kube-ctl-web:v1.0
        - export BACKEND_HOST=http://172.20.2.17:8083/
        - docker run --name kube-ctl-web --restart=always -d -p 8081:80 -e BACKEND_HOST=$BACKEND_HOST harbor.cfckube.com/kubefrank/kube-ctl-web:v1.0

